#!/bin/bash
# shellcheck disable=SC2016
set -e

(( BASH_VERSINFO[0] < 4 )) && echo "Bash 4+ required." && exit 1

: "${PAGER:=more}"
: "${EDITOR:=vi}"
: "${HELP_BROWSER:=}"
: "${EXE:="${0##*/}"}"

declare -A HELP
declare -A CONF

_initialize() {
  : "${CONF[current]:=away}"
}

_alternatives() {
  [[ $CMD = name ]] && x.mode "$@"
}

HELP[main]='
# Live Streaming Mode and Status Update Utility

This bash script helps Twitch live streamers using the command line to
keep their communities informed about what is happening on the stream in
real time by communicating the change in status (called a "mode") via
several methods (depending on what is detected and supported on the
current system):

* Twitch Title
* Twitch Category
* Twitch Chat Message
* Twitter Post
* GitHub Status

## Dependencies

Required:

* Bash 4+
* `curl`
* `jq`

Optional:

* `pandoc` - for rich help docs

## Legal

Copyright 2021 Rob Muhlestein <rob@rwx.gg>  
Released under Apache-2.0 License  
Please mention rwxrob.tv'

HELP[list]='List available modes.'

x.list () {
  local -a modes
  local mode line
  while IFS= read -r line; do
    if [[ $line =~ ^mode && $line =~ name ]]; then
      line=${line//mode./}
      mode=${line//.name/}
      modes+=($mode)
    fi
  done < <(x.config keys);
  echo $(printf "%s\n" "${modes[@]}" | sort)
}

# ------------------------------- mode -------------------------------

HELP[mode]='

```
'"$EXE"' [NEW]
```

Print the current mode name (from local cache) or set to a new one. Note
that this does not fetch the current remote Twitch status'

x.mode() { x.config current "$@";}

# ------------------------------- emoji ------------------------------

HELP[title]='

```
'"$EXE"' [NEW]
```

Print or change the current mode emoji.'

x.emoji() {
  local cur="$(x.mode)" new="$1"
  if [[ -z "$new" ]]; then
    x.config "mode.$cur.emoji"
    return $?
  fi
  x.config "mode.$cur.emoji" "$new"
}

# ------------------------------ titles ------------------------------

HELP[titles]='

```
'"$EXE"'
```

List all titles in alphabetical order by mode name.'

x.titles() {
  local cur="$(x.mode)"
  for i in $(x.list); do
    x.mode "$i"
    x.title
  done
}

# ------------------------------ status ------------------------------

HELP[status]='

```
'"$EXE"' [NEW]
```

Print or change the current mode status.
'

x.status() {
  local cur="$(x.mode)" new="$*"
  if [[ -z "$new" ]]; then
    x.config "mode.$cur.status"
    return $?
  fi
  x.config "mode.$cur.status" "$new"
}

# ------------------------------- flags ------------------------------

HELP[flags]='

```
'"$EXE"' [NEW]
```

Print or change the current mode flags. If more than one flag, each must
be separated by a single comma (no whitespace), for example: `cam,mic`.
'

x.flags() {
  local cur="$(x.mode)" new="$*"
  if [[ -z "$new" ]]; then
    x.config "mode.$cur.flags"
    return $?
  fi
  x.config "mode.$cur.flags" "$new"
}

# ----------------------------- category -----------------------------

HELP[category]='

```
'"$EXE"' [NEW]
```

Print or change the current mode category. Prints both the category ID
number and the long written form separated by a space. Note that
changing the category requires the number only and does not immediately
update the current category on Twitch, only the local entry in the
configuration data.'

x.category() {
  local cur="$(x.mode)" new="$*"
  if [[ -z "$new" ]]; then
    local id="$(x.config "mode.$cur.category")"
    local long="$(x.config "cat.$id")"
    printf "%s %s\n" "$id" "$long"
    return $?
  fi
  x.config "mode.$cur.category" "$new"
}

# ------------------------------- tags -------------------------------

HELP[tags]='

```
'"$EXE"' [NEW]
```

Print or change the current tags list. Note that changing the tags does
not update the current tags on Twitch, only the local entry in the
configuration data. Twitch limits tags to five total.'

x.tags() {
  local cur="$(x.mode)" new="$*"
  if [[ -z "$new" ]]; then
    x.config "mode.$cur.tags"
    return $?
  fi
  x.config "mode.$cur.tags" "$new"
}

# ------------------------------- title ------------------------------

HELP[title]='

```
'"$EXE"'
```

Print the current emoji, status, and flags on a single line suitable for
pasting into the Twitch Stream Info > Title field. The name of the mode
is not printed since often a gerund would be better than the simple mode
name. Add the gerund version of the mode to the status if desired. The
commas of the flags will be replaced with bars (|) and wrapped with
square brackets.
'

x.title() {
  local flags="$(x.flags)"
  flags=${flags//,/|}
  printf "%s  %s %s\n" \
    "$(x.emoji)" \
    "$(x.status)" \
    "[$flags]"
}

############################## BOILERPLATE ###########################
## Everything from here to the end of file can be snipped and updated
## with latest from https://github.com/rwxrob/template-bash-command.

# -------------------------- utility command -------------------------

HELP[usage]='Displays a summary of usage.'

x.usage() {
  local -a cmds
  for c in "${COMMANDS[@]}"; do
    [[ ${c:0:1} =~ _ ]] && continue
    cmds+=("$c")
  done
  local IFS='|'
  printf "usage: %s (%s)\n" "$EXE" "${cmds[*]}"
}

# --------------------------- help command ---------------------------

HELP[help]='

```
'"$EXE"' help [COMMAND]
```

Displays specific help information. If no argument is passed displays
general help information (main). Otherwise, the documentation for the
specific argument keyword is displayed, which usually corresponds to
a COMMAND name (but not necessarily). All documentation is written in
GitHub Flavored Markdown and will displayed as a web page if `pandoc`
and `$HELP_BROWSER` are detected, otherwise, just the Markdown is sent
to `$PAGER` (default: more).

Also see `readme` and `usage` commands.
'

x.help() { 
  local name="${1:-main}" title body
  title=$(_help_title "$name") || true
  if [[ -z "$title" ]]; then
    body="${HELP[$name]}"
    title="$EXE $name"
    [[ $name = main ]] && title="$EXE"
  else
    body="${HELP[$name]}"
    body=${body#*$title}
  fi
  local file="/tmp/help-$EXE-$name.html"
  if _have pandoc ; then
    if _have "$HELP_BROWSER" && [[ -t 1 ]] ;then
      pandoc -f gfm -s --metadata title="$title" \
        -o "$file" <<< "$body"
      [[ -z "$2" ]] && cd /tmp && exec "$HELP_BROWSER" "$file"
      return 0
    fi
    pandoc -f gfm -s --metadata title="$title" \
      -t plain <<< "$body" | "$PAGER"
    return 0
  fi
  echo -e "$title\n\n$body" | "$PAGER"
}

_help_title() {
  _filter "$@" && return $?;
  local name="$1"
  while IFS= read -r line; do
    [[ $line =~ ^[:space]*$ ]] && continue
    [[ $line =~ ^#\ (.+) ]] && echo "${BASH_REMATCH[1]}" && return 0
    return 1
  done <<< "${HELP[$name]}"
}

# -------------------------- readme command --------------------------

HELP[readme]='
## Generate `README.md` File

```
'"$EXE"' readme > README.md
```

The `readme` command will output the embedded help documentation in raw
GitHub Flavored Markdown suitable for use as a `README.md` file on
GitHub or similar hosting service.'

x.readme() {
  _trim "${HELP[main]}"
  echo
  while IFS= read -r name; do
    [[ $name = main ]] && continue
    body=$(_trim "${HELP[$name]}")
    [[ $body =~ ^\# ]] || body="## The \`$name\` Command"$'\n\n'$body
    printf "%s\n\n" "$body"
  done < <(printf "%s\n" "${!HELP[@]}" | LC_COLLATE=C sort)
  echo -e "----\n\n*Autogenerated $(date)*\n"
}

# x.json() { _jsonstr "$@"; }
# x.urlencode() { _urlencode "$@"; }

# -------------------------- config command --------------------------

HELP[config]='

```
'"$EXE"' config
'"$EXE"' config KEY
'"$EXE"' config KEY VALUE
'"$EXE"' config KEY ""
'"$EXE"' config keys
'"$EXE"' config val[ues]
'"$EXE"' config dir[ectory]
'"$EXE"' config path [file]
'"$EXE"' config edit [file]
'"$EXE"' config del[ete]
```

The `config` command is for reading, writing, and displaying standard
open desktop configuration properties. Pass an empty string to delete
a property.

### Arguments

With no arguments outputs all the currently cached configuration
settings.

With a single KEY argument fetches the value for that key and outputs
it unless it is one of the following special (reserved) key names:

* `dir*` full path to config directory
* `path` full path to specific config file (default: `values`) 
* `edit` opens config file in editor (default: `editor` or `$EDITOR)
* `keys` output the configuration keys, one per line
* `val*` output the configuration values, one per line
* `del*` if key argument then delete a specific key, otherwise prompt

With more than one argument the remaining arguments after the KEY will
be combined into the VALUE and written to a `values` file in the
configuration directory. 

### Configuration Directory

The configuration directory path relies on the following environment
variables:

* `EXE` - defaults to name of currently running command ('"$EXE"')
* `HOME` - checked for `$HOME/.config/$EXE/values`
* `XDG_CONFIG_HOME` - overrides `$HOME/.config`
* `CONFIG_DIR` - full path to directory containing `values` file

The `CONFIG_DIR` always takes priority over anything else if set, but is
never implied. If the directory does not exist it will be created the
first time a value is set.

### Configuration `values` File Format

The file (which is almost always located at
`~/.config/'"$EXE"'/values`) uses the simplest possible format to
facilitate standard UNIX parsing and filtering with any number of
existing tools (and no `jq` dependency).

* One KEY=VALUE per line
* KEYs may be anything but the equal sign (`=`)
* VALUEs may be anything but line returns must be escaped

Note that this is *not* the same as Java properties and other similar
format. It is designed for ultimate simplicity, efficiency, and
portability.'

x.config() {
  case $1 in 
    dir*) shift; _config_dir  "$@"; return $? ;;
    path) shift; _config_path "$@"; return $? ;;
    edit) shift; _config_edit "$@"; return $? ;;
    del*) shift; _config_del  "$@"; return $? ;;
    keys) shift; _config_keys "$@"; return $? ;;
    val*) shift; _config_vals "$@"; return $? ;;
  esac
  case $# in
    0) _config_dump ;;
    1) _config_get "$@" ;;
    *) _config_set "$@" ;;
  esac
}

_config_edit() {
  : "${CONF[editor]:="${EDITOR:=vi}"}"
  exec "${CONF[editor]}" "$(_config_path "${1:-values}")"
}

_config_del() {
  if [[ -z "$1" ]];then
    select key in "${!CONF[@]}"; do
      _config_del "$key"
      return $? 
    done
  fi
  _config_set "$1" ''
}

_config_keys() { printf "%s\n" "${!CONF[@]}"; }

_config_vals() { printf "%s\n" "${CONF[@]}"; }

_config_dir() {
  local dir="$HOME/.config/$EXE"
  [[ -n "$XDG_CONFIG_HOME" ]] && dir="$XDG_CONFIG_HOME/$EXE" 
  [[ -n "$CONFIG_DIR" ]] && dir="$CONFIG_DIR"
  [[ -n "$1" ]] && echo "$dir/$1" && return 0
  printf "%s" "$dir"
  [[ -t 1 ]] && echo
}

_config_path() { 
  local file=${1:-values}
  printf "%s/%s" "$(_config_dir)" "$file"
  [[ -t 1 ]] && echo
}

_config_set() {
  local key="$1"; shift; local val="$*"
  val="${val//$'\n'/\\n}"
  CONF["$key"]="$val"
  _config_write
}

_config_get() { 
  printf "${CONF[$1]}"
  [[ -t 1 ]] && echo
}

_config_read() {
  local values="$(_config_path)"
  [[ -r "$values" ]] || return 0
  while IFS= read -r line; do
    [[ $line =~ ^([^=]+)=(.+)$ ]] || continue
    CONF["${BASH_REMATCH[1]}"]="${BASH_REMATCH[2]}"
  done < "$values"
}

_config_write() {
  local dir="$(_config_dir)"
  mkdir -p "$dir"
  _config_dump > "$dir/values"
}

_config_dump() {
  (( ${#CONF[@]} == 0 )) && return 0
  paste -d=\
    <(printf "%s\n" "${!CONF[@]}") \
    <(printf "%s\n" "${CONF[@]}") \
  | sort
}

# ----------------------------- utilities ----------------------------

_jsonstr() {
  _checkdep jq || return $?
  _buffer "$@" && return $?
  jq -MRsc <<< "$1"
}

_urlencode() {
  _buffer "$@" && return $?
  local string="$1"
  local strlen=${#string}
  local encoded=""
  local pos c o
  for ((pos = 0; pos < strlen; pos++)); do
    c=${string:$pos:1}
    case "$c" in
    [-_.~a-zA-Z0-9]) o="$c" ;;
    *) printf -v o '%%%02x' "'$c'" ;;
    esac
    encoded+="$o"
  done
  echo "$encoded"
}

_reduce() {
  local -n name="${1:?"name of array required"}"
  while IFS= read -r key; do
    [[ $key =~ $2 ]] && echo "$key"
  done < <(printf "%s\n" "${name[@]}")
}

_newest() {
  IFS=$'\n'
  local -a f=($(ls -1 --color=never -trd ${1:-.}/* 2>/dev/null))
  [[ ${#f} > 0 ]] && echo "${f[-1]}"
}

_trim() {
  local it="${1#"${1%%[![:space:]]*}"}"
  echo -e "${it%"${it##*[![:space:]]}"}"
}

_have(){ type "$1" &>/dev/null; }

_checkdep() {
  _have "$1" && return 0
  echo "'$EXE' depends on '$1' for this, but not found"
  return 1
}

_filter(){
  [[ -n "$1" ]] && return 1
  while IFS= read -ra args; do
    "${FUNCNAME[1]}" "${args[@]}"
  done
}

_buffer() {
  [[ -n "$1" ]] && return 1
  "${FUNCNAME[1]}" "$(</dev/stdin)"
}

# --------------------- completion and delegation --------------------
#      `complete -C foo foo` > `source <(foo bloated_completion)`

while IFS= read -r line; do
  [[ $line =~ ^declare\ -f\ x\. ]] || continue
  COMMANDS+=( "${line##declare -f x.}" )
done < <(declare -F)
mapfile -t COMMANDS < \
  <(LC_COLLATE=C sort < <(printf "%s\n" "${COMMANDS[@]}"))

if [[ -n $COMP_LINE ]]; then
  line=${COMP_LINE#* }
  for c in "${COMMANDS[@]}"; do
    [[ ${c:0:${#line}} == "${line,,}" ]] && echo "$c"
  done
  exit
fi

_config_read
_have _initialize && _initialize "$@"

for c in "${COMMANDS[@]}"; do
  if [[ $c == "$EXE" ]]; then
    "x.$EXE" "$@"
    exit $?
  fi
done

if [[ -n "$1" ]]; then
  declare CMD="$1"; shift
  for c in "${COMMANDS[@]}"; do
    if [[ $c == "$CMD" ]]; then
      "x.$CMD" "$@"
      exit $?
    fi
  done
fi

if _have _alternatives; then
  _alternatives "$@" 
  exit $?
fi

x.usage "$@"
